### ISSUE TITLE
ImportError: cannot import name 'maybe_allow_in_graph' from 'diffusers.utils'

### ISSUE THREAD

**Issue by doogyhatts** [neggles/animatediff-cli#28]
I got this error when I tried to run it in Colab. Not sure how to resolve it.

`Traceback (most recent call last):
  File "/usr/local/bin/animatediff", line 5, in <module>
    from animatediff.cli import cli
  File "/content/animatediff-cli/src/animatediff/cli.py", line 12, in <module>
    from animatediff.generate import create_pipeline, run_inference
  File "/content/animatediff-cli/src/animatediff/generate.py", line 13, in <module>
    from animatediff.models.unet import UNet3DConditionModel
  File "/content/animatediff-cli/src/animatediff/models/unet.py", line 18, in <module>
    from .unet_blocks import (
  File "/content/animatediff-cli/src/animatediff/models/unet_blocks.py", line 9, in <module>
    from animatediff.models.attention import Transformer3DModel
  File "/content/animatediff-cli/src/animatediff/models/attention.py", line 10, in <module>
    from diffusers.utils import BaseOutput, maybe_allow_in_graph
ImportError: cannot import name 'maybe_allow_in_graph' from 'diffusers.utils' (/usr/local/lib/python3.10/dist-packages/diffusers/utils/__init__.py)`

**Comment by doogyhatts** [comment]
pip install diffusers==0.20.2

**Comment by neggles** [comment]
actually turns out the newer diffusers is what broke this. it's fixed as of c36cbc78ead5c20bbcef0cc706288f9d0d067d37 (im just pulling straight from torch instead)
