### ISSUE TITLE
Error caught was: No module named 'triton'

### ISSUE THREAD

**Issue by jygkh** [neggles/animatediff-cli#35]
(.venv) PS D:\python\animatediff-cli> animatediff generate
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.2+cu121 with CUDA 1201 (you have 2.1.2+cu118)
    Python  3.10.11 (you have 3.10.7)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Traceback (most recent call last):
  File "C:\Users\ro612\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ro612\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\python\animatediff-cli\.venv\Scripts\animatediff.exe\__main__.py", line 4, in <module>
  File "D:\python\animatediff-cli\src\animatediff\cli.py", line 12, in <module>
    from animatediff.generate import create_pipeline, run_inference
  File "D:\python\animatediff-cli\src\animatediff\generate.py", line 12, in <module>
    from animatediff.models.clip import CLIPSkipTextModel
  File "D:\python\animatediff-cli\src\animatediff\models\clip.py", line 7, in <module>
    from transformers.models.clip.modeling_clip import (
ImportError: cannot import name '_expand_mask' from 'transformers.models.clip.modeling_clip' (D:\python\animatediff-cli\.venv\lib\site-packages\transformers\models\clip\modeling_clip.py)
(.venv) PS D:\python\animatediff-cli> pip install triton
ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton

**Comment by neggles** [comment]
Looks like Transformers went and moved a function again. Sigh...

**Comment by neggles** [comment]
This shouldn't be an issue anymore - looks like the problem was related to venv packages etc.
